name: "cifar"
train_path: "train_cifar.npy"
test_path: "test_cifar.npy"
sz: 32
nc: 3
glo:
  learning_rate: 0.01
  factor: 0.1
  nz: 64
  batch_size: 128
  do_bn: False
  decay: 50
  total_epoch: 500
icp:
  dim: 32
  total_epoch: 50
fid:
  batch_size: 50
  n_images: 10000
